### ISSUE TITLE
Cytolk doesn't work insite PyInstaller

### ISSUE THREAD

**Issue by chrisnorman7** [pauliyobo/cytolk#1]
Hi mate,
When building a script which uses Cytolk with PyInstaller, I have to then go int the dist directory, and place the DLLs.

Is there any way you could submit a PR to pyinstaller to include the DLLs automatically?

Just saves that extra step.

Thanks in advance.

**Comment by pauliyobo** [comment]
Hello. I've added a pyinstaller hook which should copy the libraries automatically.
Are you able to test it on your end and tell me if it works? I've tested it under python 3.9 and it seems to work over here
to add the hook, simply copy the file in hooks/hook-cytolk.py in Pyinstaller/hooks.

**Comment by chrisnorman7** [comment]
OK, I'll give it a go now.

Take care,

Chris Norman

**Comment by chrisnorman7** [comment]
Works perfectly. Good job.

Take care,

Chris Norman

**Comment by pauliyobo** [comment]
@chrisnorman7 good to hear. I'm going to go ahead and consider this issue closed. Thanks for the feedback.

**Comment by chrisnorman7** [comment]
Sorry, I should have done it myself, but I was replying via email, and I
forgot.

Good job on the hook.

Take care,

Chris Norman
