### ISSUE TITLE
DLL extracting fails on certain machines.

### ISSUE THREAD

**Issue by TheQuinbox** [pauliyobo/cytolk#3]
This doesn't happen on all machines, but does in some cases. This was what caused Crime Hunter to not use Cytolk, in fact. On certain machines, with the DLLs imbedded inside the exe, the following is written to the log. DO note that -onefile was not used, as far as I'm aware. Just used whatever function cytolk uses to let you imbed the DLLs.
Traceback (most recent call last):
  File "ch.pyw", line 25, in <module>
  File "framework.py", line 12, in init framework
  File "c:\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "cytolk\__init__.py", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.

**Comment by pauliyobo** [comment]
Hi
@TheQuinbox 
A nuitka plugin was added  and it should take care of copying the various libraries needed in the final executable, be it standalone or onefile. When running nuitka you should pass the option
--user-plugin=path-to-plugin which on here is nuitka_plugin/CytolkPlugin.py
Could you test on your end if it works before I push the release?
You can install it manually or grab one of the artifacts of the latest build [here](https://github.com/pauliyobo/cytolk/actions/runs/1402887527#artifacts)
Thanks.

**Comment by TheQuinbox** [comment]
Yeah, grabbing now. Thanks so much for this!

**Comment by TheQuinbox** [comment]
Yup, this seems to have fixed it. Awesome!
